repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "f5c26753e4c8a1f45b9d7edefa976fe4ea932e26"
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  # - repo: https://github.com/hakancelik96/unimport
  #   rev: 0.8.3
  #   hooks:
  #     - id: unimport
  #       args: [--remove, --include-star-import]
  - repo: https://github.com/pycqa/isort
    rev: "c6a41965247a858a0afd848fbebfca18b8983917"
    hooks:
      - id: isort
        files: "pp/.*"
        args: ["--profile", "black", "--filter-files"]

  - repo: https://github.com/psf/black
    rev: "fb8dfdeec5fd76cc0c30f881d6fc75851139d80a"
    hooks:
      - id: black

  - repo: https://github.com/kynan/nbstripout
    rev: 8cafdcc393232045208137698dbeb42d6e0dd9e8
    hooks:
      - id: nbstripout
        files: ".ipynb"

  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: "214c33306afe17f1cc7d2d55e4da705b6ebe0627"
  #   hooks:
  #       - id: mypy
  #         exclude: ^(docs/|example-plugin/|tests/fixtures)
  # - repo: https://github.com/pycqa/pydocstyle
  #   rev: "b174899473013ab2408eb758e36bb5cf17bbfa17"
  #   hooks:
  # - id: pydocstyle
  # - repo: https://gitlab.com/pycqa/flake8
  #   rev: "a252652abb05cda1a267ac836b05d58a708ae9b6"
  #   hooks:
  #       - id: flake8
